version: "3"
services:
    api:
        build: api
        ports:
            - "5000:5000"
        env_file:
            - database.env
        environment:
            - POSTGRES_HOST=database
            - POSTGRES_PORT=5432
    database:
        build: database
        ports:
            - "5432:5432"
        env_file:
            - database.env
        volumes:
            - ./database/data:/var/lib/postgresql/data
